version: "3"
services:
  kino-premium:
    container_name: kino-premium
    hostname: kino-premium
    build: .
    env_file: .env
    ports:
      - "5176:5176"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    